HOSTS:
  ubuntu1604-64:
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:16.04
    platform: ubuntu-16.04-amd64
    packaging_platform: ubuntu-16.04-amd64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - apt-get install -y net-tools wget locales apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    hypervisor: docker
