# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.2.0"

# Require 1.2.x at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # ip addresses are used in /etc/icinga2/cluster/cluster.conf (!)
  servers = { 'icinga2m' => '192.168.33.100',
	      'icinga2a1' => '192.168.33.110',
	      'icinga2a2' => '192.168.33.120'
            }
  http_port = { 'icinga2m' => 8100,
	        'icinga2a1' => 8101,
	        'icinga2a2' => 8102
              }
  ssh_port = { 'icinga2m' => 2100,
	       'icinga2a1' => 2101,
	       'icinga2a2' => 2102
             }

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |app_config|
      app_config.vm.box = "centos-6.5-i386-vbox"
      app_config.vm.box_url = "http://boxes.icinga.org/centos-65-i386-vbox.box"
      app_config.vm.hostname = "#{server_name.to_s}"
      app_config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      app_config.vm.network :forwarded_port, guest: 22, host: ssh_port[server_name], auto_correct: true
      app_config.vm.network :forwarded_port, guest: 80, host: http_port[server_name], auto_correct: true
      app_config.vm.network :private_network, ip: "#{server_ip}"
      app_config.vm.provider "virtualbox" do |vb|
        vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate//vagrant/config", "1"]
	vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      app_config.vm.provision :puppet do |puppet|
        puppet.module_path = ".vagrant-puppet/modules"
        puppet.manifests_path = ".vagrant-puppet/manifests"
        #puppet.options = "--verbose --debug"
      end
      app_config.vm.provision :shell, :path => ".vagrant-puppet/manifests/finalize.sh"
    end
  end
end

