# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.6.5"

# Require 1.6.5 at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # ip addresses are used in /etc/icinga2/cluster/cluster.conf (!)
  servers = { 'icinga2a' => '192.168.33.101',
	      'icinga2b' => '192.168.33.102',
	      'icinga2c' => '192.168.33.103'
            }
  http_port = { 'icinga2a' => 8085,
	        'icinga2b' => 8086,
	        'icinga2c' => 8087
              }
  ssh_port = { 'icinga2a' => 2085,
	       'icinga2b' => 2086,
	       'icinga2c' => 2087
             }

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |app_config|
      app_config.vm.hostname = "#{server_name.to_s}"
      app_config.vm.network :forwarded_port, guest: 22, host: ssh_port[server_name], auto_correct: true
      app_config.vm.network :forwarded_port, guest: 80, host: http_port[server_name], auto_correct: true
      app_config.vm.network :private_network, ip: "#{server_ip}"

      app_config.vm.provision :shell, :path => "manifests/puppet.sh"

      # parallels
      app_config.vm.provider :parallels do |p, override|
        override.vm.box = "parallels/centos-7.2"

        p.name = "Icinga 2: #{server_name.to_s}"

        # Update Parallels Tools automatically
        p.update_guest_tools = true

        override.vm.boot_timeout = 600

        # save storage
        p.linked_clone = true

        # Set power consumption mode to "Better Performance"
        p.customize ["set", :id, "--longer-battery-life", "off"]

        p.memory = 1024
        p.cpus = 1
      end

      # virtualbox
      app_config.vm.provider :virtualbox do |v, override|
        override.vm.box = "centos-71-x64-vbox"
        override.vm.box_url = "http://boxes.icinga.org/centos-71-x64-vbox.box"

        v.customize ["modifyvm", :id, "--memory", "1024"]
        v.customize ["modifyvm", :id, "--cpus", "2"]
        # Using the host's resolver as a DNS proxy in NAT mode
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

        # save storage
        v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      end

      app_config.vm.provider :libvirt do |l, override|
        override.vm.box = "centos/7"

        l.memory = 1024
        l.cpus = 1
      end

      # provisioner
      app_config.vm.provision :puppet do |puppet|
        puppet.module_path = "../modules"
        puppet.manifests_path = "manifests"
        puppet.hiera_config_path = "hiera.yaml"
        #puppet.options = "--verbose --debug"
        puppet.options = "--parser=future"
      end
      app_config.vm.provision :shell, :path => "manifests/finalize.sh"
    end
  end
end

