# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.6.5"

# Require 1.6.5 at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # ip addresses are used in /etc/icinga2/cluster/cluster.conf (!)
  servers = { 'icinga2a' => '192.168.33.10',
	      'icinga2b' => '192.168.33.20'
            }
  http_port = { 'icinga2a' => 8085,
	        'icinga2b' => 8086
              }
  ssh_port = { 'icinga2a' => 2085,
	       'icinga2b' => 2086
             }

  servers.each do |server_name, server_ip|
    config.vm.define server_name do |app_config|
      app_config.vm.box = "centos-71-x64-vbox"
      app_config.vm.box_url = "http://boxes.icinga.org/centos-71-x64-vbox.box"
      app_config.vm.hostname = "#{server_name.to_s}"
      app_config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
      app_config.vm.network :forwarded_port, guest: 22, host: ssh_port[server_name], auto_correct: true
      app_config.vm.network :forwarded_port, guest: 80, host: http_port[server_name], auto_correct: true
      app_config.vm.network :private_network, ip: "#{server_ip}"
      app_config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
      app_config.vm.provision :puppet do |puppet|
        puppet.module_path = "../modules"
        puppet.manifests_path = "manifests"
        puppet.hiera_config_path = "hiera.yaml"
        puppet.options = "--verbose --debug"
      end
      app_config.vm.provision :shell, :path => "manifests/finalize.sh"
    end
  end
end

