# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.6.5"

# Require 1.6.5 at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-71-x64-vbox"
  config.vm.box_url = "http://boxes.icinga.org/centos-71-x64-vbox.box"
  config.vm.hostname = "icinga2.demo.icinga.org"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2080, auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 8080, auto_correct: true
  config.vm.network :forwarded_port, guest: 5668, host: 5668, auto_correct: true
  config.vm.network :private_network, ip: "192.168.56.200"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "../modules"
    puppet.manifests_path = "manifests"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.options = "--verbose --debug"
  end
  config.vm.provision :shell, :path => "manifests/finalize.sh"
end

