---
.gitignore:
  required:
    - ---.project

.travis.yml:
  unmanaged: true

Gemfile:
  optional:
    ':development':
      - gem: puppet-lint-i18n
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

appveyor.yml:
  unmanaged: true

Rakefile:
  requires:
    - puppet_pot_generator/rake_tasks
  changelog_user: 'puppetlabs'

spec/spec_helper.rb:
  spec_overrides:
    -  "require 'spec_helper_local'"

.rubocop.yml:
   default_configs:
    inherit_from: .rubocop_todo.yml
    require:
      - rubocop-i18n
      - rubocop-rspec

.gitlab-ci.yml:
  unmanaged: true
