plantuml -tpng workflow.plantum

@startuml
start

if (Install?) then (yes)
  :Install packages;
  :Configure;
  fork
    :Compile modules;
  fork again
    :Manage port-contexts (delete);
  fork again
    :Manage permissive-domains (delete);
  end fork
  :Manage modules;
  fork
    :Manage booleans;
  fork again
    :Manage file-contexts;
  fork again
    :Manage port-contexts (add/modify);
  fork again
    :Manage permissive-domains (add);
  end fork
  :Manage runtime mode;
else (no)
  :Uninstall packages;
endif

stop
@enduml
