# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.6.5"

# Require 1.6.5 at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-6.4-x64-vbox"
  config.vm.box_url = "http://vagrant-boxes.icinga.org/centos-64-x64-vbox4212.box"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2090, auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 8090, auto_correct: true
  config.vm.network :forwarded_port, guest: 2003, host: 20003, auto_correct: true
  config.vm.network :forwarded_port, guest: 2004, host: 20004, auto_correct: true
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "modules"
    puppet.manifests_path = "manifests"
    puppet.options = "--verbose --debug"
  end
  config.vm.provision :shell, :path => "manifests/finalize.sh"
end

