# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VAGRANT_REQUIRED_VERSION = "1.6.5"

# Require 1.6.5 at least
if ! defined? Vagrant.require_version
  if Gem::Version.new(Vagrant::VERSION) < Gem::Version.new(VAGRANT_REQUIRED_VERSION)
    puts "Vagrant >= " + VAGRANT_REQUIRED_VERSION + " required. Your version is " + Vagrant::VERSION
    exit 1
  end
else
  Vagrant.require_version ">= " + VAGRANT_REQUIRED_VERSION
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos-70-x64-vbox"
  config.vm.box_url = "http://boxes.icinga.org/centos-70-x64-vbox.box"
  config.vm.hostname = "g2i2.demo.icinga.org"
  config.vm.network :forwarded_port, guest: 22, host: 2232, id: "ssh", disabled: true
  config.vm.network :forwarded_port, guest: 22, host: 2119, auto_correct: true
  config.vm.network :forwarded_port, guest: 80, host: 8110, auto_correct: true
  # we need to keep the same ports, since re-configuration requires -server/-web cfg changes
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp', auto_correct: true
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp', auto_correct: true
  config.vm.network :forwarded_port, guest: 12900, host: 12900
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "../modules"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.options = "--verbose --debug"
  end
  # add gelf inputs etc
  config.vm.provision :shell, :path => "scripts/graylog2-seed.rb"
  # tell the user where to login
  config.vm.provision :shell, :path => "scripts/finalize.sh"
end

