---
dist: xenial
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script: 
  - 'bundle exec rake validate lint spec'
rvm:
  - 2.4.4
env:
  - PUPPET_GEM_VERSION="~> 4.0"
  - PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
notifications:
  email: false
