HOSTS:
  ubuntu-server-1204-x64:
    roles:
      - master
    platform: ubuntu-1204-amd64
    box: puppetlabs/ubuntu-12.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-12.04-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
  vagrant_ssh_port_random: true