fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    concat: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
