fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    stdlib: "#{source_dir}"
    test:   "#{source_dir}/spec/fixtures/test"