---
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
env:
  global:
    - PUPPET_GEM_VERSION="~> 6.0"
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=debian_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_debian]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=debian_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_debian]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el6_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el6]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el6_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el6]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el7_puppet5
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el7]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el7_puppet6
      rvm: 2.5.3
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el7]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:parallel
      services: docker
      sudo: required
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"