sudo: false
cache: bundler
language: ruby
bundler_args: --without system_tests development
script: "bundle exec rake spec"
rvm:
  - 2.1.0
  - 2.3.1
env:
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
matrix:
  exclude:
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes
    - rvm: 2.3.1
      env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
notifications:
  email: false
branches:
  only:
  - master
  - /^v\d/
