fixtures:
  repositories:
    archive: "git://github.com/voxpupuli/puppet-archive.git"
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'
  symlinks:
    java: "#{source_dir}"
