---
sudo: required
services:
- docker

before_install: rm Gemfile.lock || true
bundler_args: --without development
cache:
  bundler: true
  directories:
  - spec/fixtures/artifacts
  - spec/fixtures/modules

language: ruby

script: travis_retry bundle exec rake $TASK

jobs:
  include:
   - stage: intake
     env:
     - TASK=test
     - PUPPET_VERSION='~> 4.10.0'
   - env:
     - TASK=test
   - env:
     - TASK=test
     - PUPPET_VERSION='~> 5.0'
   - stage: acceptance
     env:
     - TASK=beaker:amazonlinux-x64
   - env:
     - TASK=beaker:centos-6-x64
   - env:
     - TASK=beaker:centos-7-x64
   - env:
     - TASK=beaker:debian-7-x64
   - env:
     - TASK=beaker:debian-8-x64
   - env:
     - TASK=beaker:ubuntu-1404-x64
   - env:
     - TASK=beaker:ubuntu-1604-x64
   - env:
     - TASK=beaker:fedora-28-x64
   - stage: snapshots
     env:
     - TASK=beaker:ubuntu-1604-x64:snapshot
   - env:
     - OSS_PACKAGE=true
     - TASK=beaker:ubuntu-1604-x64:snapshot
   - env:
     - TASK=beaker:centos-7-x64:snapshot
   - env:
     - OSS_PACKAGE=true
     - TASK=beaker:centos-7-x64:snapshot

notifications:
  slack:
    secure: T1FO+ttrJNH+bXmNR6349qcttG68Qr1xmMqVVRnUr7+129GQO5174Z8MFC8ck0qOCZGHO7GCNO5seNFflrjF/5EKbdkmVnqhf9gVa9kN7I4psMzxJX9bp29xJA6m3wA4VqCosDKVFSfilDZujAblWT+KDHZLjP8sEWEnHPvCjf69S2XDQEWUoxZan5V9IJQas4XR+hMdIZTA3ChVrEyqRfeehAZImbAr/LH8zChZaTdHZQY7p2rN3+qVNi3+GISV9fNPpOCynnX/ACbdUaRt3+1etxGGaQMPzGmTejN3VlMw4OZRXImb6HQ2rXE+fNCASXiKiwylxTbriQsS0dFv4skxH03YlYM8pqaBpeIOwzf4n45tTzdAQZJMC5cOb+RvwS7qkAwuaVlVxiiA+MWRG/UcFpWS+iNn4KEKxbpBjYP8X1JIP9DlHLME7DNMM2pePv9X6ZjY6eDhVM1gbKi77dXOo5y2Sp0ru8QkLpIKFVXS01O+x7oDHHv2Osvih0jNMgM66Byso3KJYJ6EJ0D2/3Q9ZNpVM4CMuIY5pBQfXf691zqkBHI6JUnU6VMw97cH0k6Gq0ypZoW5trXdnRC5aEg4jKKid84zKmAeTpj/iMuagyb/a5msJstIVboynRtfDHR0J8WWhfSU2wzqKAb6L66iyRe62Fe8OGzLhk2+KNU=
