HOSTS:
  centos7-64:
    docker_cmd:
      - "/sbin/init"
    image: centos:7
    platform: el-7-x86_64
    packaging_platform: el-7-x86_64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - yum install -y crontabs initscripts iproute openssl sysvinit-tools tar wget
        which ss
    hypervisor: docker
    roles: []
