HOSTS:
  ubuntu1404-64:
    docker_cmd:
      - "/sbin/init"
    image: ubuntu:14.04
    platform: ubuntu-14.04-amd64
    packaging_platform: ubuntu-14.04-amd64
    docker_image_commands:
      - cp /bin/true /sbin/agetty
      - rm /usr/sbin/policy-rc.d
      - rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl
      - apt-get install -y net-tools wget apt-transport-https
      - locale-gen en_US.UTF-8
      - echo LANG=en_US.UTF-8 > /etc/default/locale
    hypervisor: docker
